LOOK_R = '( ◉_◉)'
LOOK_L = '(◉_◉ )'
LOOK_R_HAPPY = '( ◉‿◉)'
LOOK_L_HAPPY = '(◉‿◉ )'
SLEEP = '(ᵕ_ᵕ)'
SLEEP2 = '(¬_¬)'
AWAKE = '(◉‿◉)'
BORED = '(◉_◉)'
INTENSE = '(⊙_⊙)'
COOL = '(⌐◉_◉)'
HAPPY = '(◉‿◉)'
GRATEFUL = '(^◉◉^)'
EXCITED = '(✦‿✦)'
MOTIVATED = '(☼_☼)'
DEMOTIVATED = '(._.)'
SMART = '(✜_✜)'
LONELY = '(◉︵◉)'
SAD = '(╥_╥)'
ANGRY = '(ಠ_ಠ)'
FRIEND = '(♥_♥)'
BROKEN = '(×_×)'
DEBUG = '(#_#)'
UPLOAD = '(↑_↑)'
UPLOAD1 = '(↑‿↑)'
UPLOAD2 = '(↥_↥)'


def load_from_config(config):
    for face_name, face_value in config.items():
        globals()[face_name.upper()] = face_value
